/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Estructuras.Lista;
import Estructuras.Cola;
import Estructuras.Nodo;
import Politicas.Proceso;
import javax.swing.*;
import java.awt.*;
import java.util.Random; // Random está permitido para valores aleatorios, no es una colección

/**
 *
 * @author Miguel
 */
public class Ventana extends javax.swing.JFrame {

    private JTextArea areaConsola;
    private Lista<Proceso> listaMaestra;
    private Random random;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        setTitle("Simulador de Planificación de Procesos - Isabel");
        setSize(800, 600);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        random = new Random();
        listaMaestra = new Lista<>();
        areaConsola = new JTextArea();
        areaConsola.setBackground(Color.BLACK);
        areaConsola.setForeground(Color.GREEN);
        areaConsola.setEditable(false);
        
        JScrollPane scroll = new JScrollPane(areaConsola);
        add(scroll, BorderLayout.CENTER);

        // Panel de Botones
        JPanel panelBotones = new JPanel();
        JButton btnMasivo = new JButton("Generar 20 Procesos Aleatorios");
        JButton btnEmergencia = new JButton("Añadir Tarea de Emergencia");
        JButton btnEjecutarRR = new JButton("Ejecutar Round Robin");

        panelBotones.add(btnMasivo);
        panelBotones.add(btnEmergencia);
        panelBotones.add(btnEjecutarRR);
        add(panelBotones, BorderLayout.SOUTH);

        // --- Eventos ---
        
        btnMasivo.addActionListener(e -> generarProcesos(20));
        
        btnEmergencia.addActionListener(e -> {
            generarProcesos(1);
            areaConsola.append("\n[!] Tarea de emergencia añadida a la lista.\n");
        });

        btnEjecutarRR.addActionListener(e -> ejecutarSimulacion());

        // Configuración Inicial Dinámica (Al arrancar)
        generarProcesos(5);
        setVisible(true);
    }
    
    private void generarProcesos(int cantidad) {
        for (int i = 0; i < cantidad; i++) {
            int rafaga = random.nextInt(15) + 1;
            int prioridad = random.nextInt(10) + 1;
            String id = "P" + (listaMaestra.size() + 1);
            Proceso nuevo = new Proceso(id, rafaga, prioridad);
            listaMaestra.agregarAlFinal(nuevo);
            areaConsola.append("Creado: " + id + " | Ráfaga: " + rafaga + " | Prioridad: " + prioridad + "\n");
        }
    }

    private void ejecutarSimulacion() {
        if (listaMaestra.estaVacia()) {
            JOptionPane.showMessageDialog(this, "No hay procesos para ejecutar.");
            return;
        }

        areaConsola.append("\n--- Iniciando Ejecución RR (Quantum: 3) ---\n");
        
        // Convertimos Lista a tu clase Cola para el Round Robin
        Cola<Proceso> colaEjecucion = new Cola<>();
        Nodo<Proceso> actual = listaMaestra.getCabeza();
        while (actual != null) {
            colaEjecucion.encolar(actual.getDato());
            actual = actual.getSiguiente();
        }

        int tiempo = 0;
        int quantum = 3;

        while (!colaEjecucion.estaVacia()) {
            Proceso p = colaEjecucion.desencolar();
            int tiempoEje = (p.tiempoRestante > quantum) ? quantum : p.tiempoRestante;
            
            areaConsola.append("[T=" + tiempo + "] Ejecutando " + p.nombre + " por " + tiempoEje + "ms\n");
            
            p.tiempoRestante -= tiempoEje;
            tiempo += tiempoEje;

            if (p.tiempoRestante > 0) {
                colaEjecucion.encolar(p);
            } else {
                areaConsola.append("   >> " + p.nombre + " terminado.\n");
            }
        }
        areaConsola.append("--- Fin de la Simulación en T=" + tiempo + " ---\n");
        // Limpiamos lista maestra para nueva prueba
        listaMaestra = new Lista<>(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SwingUtilities.invokeLater(Ventana::new);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
